### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by Muscobaldi** [barbaramartina/swiftuicatalog#36]
Hi, 

Sorry if this has been reported elsewhere….

SwiftUICatalog does not display correctly if the device is set Dark Mode (I’m using iPad Pro series 3). Black text and other items appear black on a black background.

**Comment by barbaramartina** [comment]
Thanks Muscobaldi for your report :).
Is true. There is no work at all done for dark mode.
You're invited to join, you can fork the project and make a PR, I'll
happily include it.

**Comment by barbaramartina** [comment]
@Muscobaldi dark mode is now ON :)
